name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: docker build -t my-node-app .

      - name: Tag Image
        run: docker tag my-node-app:latest ${{ secrets.ECR_REPO_URI }}:latest

      # uncompromised version (v0.35.0)
      - name: Scan Image with Trivy
        uses: aquasecurity/trivy-action@v0.35.0
        with:
          image-ref: my-node-app
          format: table
          exit-code: 0

      - name: Push to ECR
        run: docker push ${{ secrets.ECR_REPO_URI }}:latest

      - name: Update kubeconfig
        run: aws eks --region ap-south-1 update-kubeconfig --name my-cluster

      - name: Deploy to EKS
        run: |
          kubectl set image deployment/node-app node-app=${{ secrets.ECR_REPO_URI }}:latest
          kubectl rollout status deployment/node-app
